config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'static_pages#top'
  resources :introductions, only: [:show]
  resources :questions, only: [:show]
  resources :answers, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :profiles do
    resources :events do
      collection do
        patch :update_all
      end
    end
    resources :albums
  end
  resources :calendars, only: [:index]
  resources :groups, only: [:create, :index, :edit, :update, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ai_message', to: 'openai_api#show'

  get 'line_qr_code', to: 'static_pages#line_qr_code'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'
  get 'how_to_use', to: 'static_pages#how_to_use'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :images, only: [:destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login

  def top; end
  def line_qr_code; end
  def line_policy; end
  def privacy_policy; end
  def terms; end
  def how_to_use; end
end

app/views/static_pages/_carousel_item_mobile.html.erb
<div class="carousel-item flex-col items-center">
  <h2 class="text-base sm:text-lg md:text-xl mb-4">
    <%= title_line1 %><br>
    <%= title_line2 %><br>
  </h2>
  <div class="<%= id %> mb-20 relative border-gray-800 dark:border-gray-800 bg-gray-800 border-[14px] rounded-[2.5rem] h-[556px] w-[278px] md:h-[600px] md:w-[300px]">
    <div class="h-[32px] w-[3px] bg-gray-800 dark:bg-gray-800 absolute -start-[17px] top-[72px] rounded-s-lg"></div>
    <div class="h-[46px] w-[3px] bg-gray-800 dark:bg-gray-800 absolute -start-[17px] top-[124px] rounded-s-lg"></div>
    <div class="h-[46px] w-[3px] bg-gray-800 dark:bg-gray-800 absolute -start-[17px] top-[178px] rounded-s-lg"></div>
    <div class="h-[64px] w-[3px] bg-gray-800 dark:bg-gray-800 absolute -end-[17px] top-[142px] rounded-e-lg"></div>
    <div class="rounded-[2rem] overflow-hidden w-[250px] h-[526px] md:w-[272px] md:h-[572px] bg-white dark:bg-gray-800">
      <a href="<%= image_url %>"><img src="<%= image_url %>" class="w-[250px] h-[526px] md:w-[272px] md:h-[572px]" alt="Image"/></a>
    </div>
  </div>
</div>

app/views/static_pages/_carousel_item_pc.html.erb
<div class="carousel-item flex-col items-center">
  <h2 class="text-base sm:text-lg md:text-xl mb-4"><%= title %></h2>
  <div class="relative mx-auto border-gray-800 dark:border-gray-800 bg-gray-800 border-[8px] rounded-t-xl h-[172px] max-w-[301px] md:h-[250px] md:max-w-[400px]">
    <div class="rounded-lg overflow-hidden h-[156px] md:h-[235px] bg-white dark:bg-gray-800">
      <a href="<%= image_url %>">
        <img src="<%= image_url %>" alt="Image from Gyazo" class="<%= img_class %>"/>
      </a>
    </div>
  </div>
  <div class="relative mx-auto bg-gray-900 dark:bg-gray-700 rounded-b-xl rounded-t-sm h-[17px] max-w-[351px] md:h-[21px] md:max-w-[597px]">
    <div class="absolute left-1/2 top-0 -translate-x-1/2 rounded-b-xl w-[56px] h-[5px] md:w-[96px] md:h-[8px] bg-gray-800"></div>
  </div>
</div>

app/views/static_pages/line_qr_code.html.erb
<% content_for(:tab_title, "LINE QRコード") %>

<h1 class="text-2xl md:text-4xl font-semibold text-center mt-10">LINE通知を受けとる設定</h1>
<div id="main" class="flex w-full h-fit mt-20 flex-col items-center sm:flex-row sm:items-start">
  <div id="left-side" class="flex w-full sm:w-1/2 items-center flex-col h-1/2 p-2 mb-10 sm:mb-0">
    <h2 class="text-xl md:text-3xl font-semibold text-center mb-5 sm:mb-16">設定①</h2>
    <p class="text-md md:text-2xl text-center mb-4">Stay FriendsのLINE公式アカウントに、<br>友達登録をしてね！</p>
    <%= image_tag "line_qr_code.png", class:"w-24 h-auto md:w-48 md:mb-8" %>
    <p class="text-xs md:text-xl">LINE公式アカウントID: @589vljjq</p>
  </div>
  <div id="right-side" class="flex w-full sm:w-1/2 items-center flex-col h-1/2 p-2">
    <h2 class="text-xl md:text-3xl font-semibold text-center mb-5 sm:mb-16">設定②</h2>
    <p class="text-md md:text-2xl text-center">LINEログインをしてね！</p>
    <p class="text-sm md:text-lg text-center mb-5 sm:mb-16">※メールアドレスでアカウント登録した人のみ</p>
    <div class="flex justify-center">
      <%= link_to auth_at_provider_path(provider: :line) do %>
        <%= image_tag "btn_login_base.png", class:"w-24 md:w-32 h-auto"%>
      <% end %>
    </div>
  </div>
</div>
<div class="flex justify-center w-full mt-10">
  <%= link_to '前の画面に戻る', request.referer, class:"text-center link" %>
</div>

app/views/static_pages/privacy_policy.html.erb
<div class="bg-white p-6 mx-auto flex justify-center mb-20 md:mb-0">
  <div class="w-full max-w-screen-lg">
    <h1 class="text-3xl font-bold mb-6 text-center">プライバシーポリシー</h1>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">お客様から取得する情報</h2>
      <p class="mb-4">当社は、お客様から以下の情報を取得します。</p>
      <ul class="list-disc pl-6 space-y-2">
        <li>氏名(ニックネームやペンネームも含む)</li>
        <li>年齢または生年月日</li>
        <li>性別</li>
        <li>職業、職歴、学歴</li>
        <li>メールアドレス</li>
        <li>電話番号</li>
        <li>住所</li>
        <li>写真や動画</li>
        <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
        <li>Cookie (クッキー)を用いて生成された識別情報</li>
        <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
        <li>当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴</li>
        <li>当社アプリの起動時間、入力履歴、購買履歴等の当社アプリの利用履歴</li>
        <li>お客様の位置情報</li>
      </ul>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">お客様の情報を利用する目的</h2>
      <p class="mb-4">当社は、お客様から取得した情報を、以下の目的のために利用します。</p>
      <ul class="list-disc pl-6 space-y-2">
        <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当社サービスの利用履歴を管理するため</li>
        <li>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</li>
        <li>広告の配信、表示及び効果測定のため</li>
        <li>お客様の趣味嗜好にあわせたターゲティング広告を表示するため</li>
        <li>当社のサービスに関するご案内をするため</li>
        <li>お客様からのお問い合わせに対応するため</li>
        <li>当社の規約や法令に違反する行為に対応するため</li>
        <li>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
        <li>当社規約の変更等を通知するため</li>
        <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
      </ul>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">安全管理のために講じた措置</h2>
      <p>当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第三者提供</h2>
      <p class="mb-4">当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第16条第3項）に該当するものについては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
      <p class="mb-4">但し、次の場合は除きます。</p>
      <ul class="list-disc pl-6 space-y-2">
        <li>個人データの取扱いを外部に委託する場合</li>
        <li>当社や当社サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">アクセス解析ツール</h2>
      <p>当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスはトラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは<%= link_to 'こちら', 'https://marketingplatform.google.com/about/analytics/terms/jp/', class: "link text-blue-600" %>からご確認ください。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">プライバシーポリシーの変更</h2>
      <p>当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">お問い合わせ</h2>
      <p>お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、<%= link_to "お問い合わせフォーム", "https://forms.gle/jj8fcaibi2Tvb9Yt7", class: "link text-blue-600" %>よりご連絡ください。</p>
      <p>この場合、必ず、運転免許証のご提示等当社が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。</p>
    </div>
  </div>
</div>

app/views/static_pages/terms.html.erb
<div class="bg-white p-6 mx-auto flex justify-center mb-20 md:mb-0">
  <div class="w-full max-w-screen-lg">
    <h1 class="text-3xl font-bold mb-6 text-center">利用規約</h1>
    <p class="mb-4">この利用規約（以下、「本規約」といいます。）は、「Stay Friends」（以下、「当社」といいます。）がこのウェブサイト上で提供するサービス（以下、「本サービス」といいます）の利用条件を定めるものです。ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。</p>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第1条（適用）</h2>
      <p class="mb-4">本規約は、ユーザーと運営者との間の本サービスの利用に関わる一切の関係に適用されます。運営者は、本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）を設ける場合があります。これら個別規定は、その名称にかかわらず本規約の一部を構成するものとします。</p>
      <p class="mb-4">本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第2条（利用登録）</h2>
      <p class="mb-4">本サービスにおいては、登録希望者が本規約に同意の上、運営者の定める方法によって利用登録を申請し、運営者がこれを承認することで利用登録が完了します。運営者は、以下のいずれかの事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負いません。</p>
      <ol class="list-decimal pl-6 space-y-2">
        <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他、運営者が利用登録を相当でないと判断した場合</li>
      </ol>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第3条（ユーザーIDおよびパスワードの管理）</h2>
      <p class="mb-4">ユーザーは、自己の責任において、ユーザーIDおよびパスワードを適切に管理しなければなりません。ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与、共用することはできません。運営者は、ユーザーIDおよびパスワードが第三者によって使用されたことによって生じた損害について、運営者に故意または重大な過失がある場合を除き、一切の責任を負いません。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第4条（禁止事項）</h2>
      <p class="mb-4">ユーザーは、本サービスの利用に際して、以下の行為をしてはなりません。</p>
      <ol class="list-decimal pl-6 space-y-2">
        <li>法令または公序良俗に違反する行為</li>
        <li>犯罪行為に関連する行為</li>
        <li>本サービスに含まれる著作権、商標権、その他知的財産権を侵害する行為</li>
        <li>運営者や他のユーザー、第三者のサーバーまたはネットワークの機能を破壊または妨害する行為</li>
        <li>本サービスの運営を妨害する行為</li>
        <li>不正アクセス行為</li>
        <li>当社のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>他のユーザーの個人情報を無断で収集、蓄積する行為</li>
        <li>本サービスの他のユーザーまたは第三者に不利益、損害、不快感を与える行為</li>
        <li>以下の表現を含み、または含むと当社が判断する内容を本サービス上に投稿し、または送信する行為
          <ol class="list-decimal pl-6 space-y-2">
            <li>過度に暴力的な表現</li>
            <li>露骨な性的表現</li>
            <li>人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現</li>
            <li>自殺、自傷行為、薬物乱用を誘引または助長する表現</li>
            <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
          </ol>
        </li>
        <li>以下を目的とし、または目的とすると当社が判断する行為
          <ol class="list-decimal pl-6 space-y-2">
            <li>営業、宣伝、広告、勧誘、その他営利を目的とする行為（当社の認めたものを除きます。）</li>
            <li>性行為やわいせつな行為を目的とする行為</li>
            <li>面識のない異性との出会いや交際を目的とする行為</li>
            <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
            <li>当方、本サービスの他のユーザー、または第三者に不利益、損害または不快感を与えることを目的とする行為</li>
            <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
            <li>宗教活動または宗教団体への勧誘行為</li>
          </ol>
        </li>
        <li>その他、運営者が不適切と判断する行為</li>
      </ol>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第5条（本サービスの提供の停止等）</h2>
      <p class="mb-4">運営者は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができます。</p>
      <ol class="list-decimal pl-6 space-y-2">
        <li>本サービスに関わるシステムの保守点検や更新を行う場合</li>
        <li>地震、火災、停電、天災などの不可抗力によって本サービスの提供が困難となった場合</li>
        <li>その他、運営者が本サービスの提供が困難と判断した場合</li>
      </ol>
      <br>
      <p class="mb-4">運営者は、サービスの提供の停止または中断によって生じた損害について、一切の責任を負いません。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第6条（利用制限および登録抹消）</h2>
      <p class="mb-4">運営者は、ユーザーが以下のいずれかに該当する場合には、事前通知なく、本サービスの利用を制限し、またはユーザーの登録を抹消することができます。</p>
      <ol class="list-decimal pl-6 space-y-2">
        <li>本規約に違反した場合</li>
        <li>虚偽の登録情報を提供した場合</li>
        <li>長期間にわたりサービスの利用がない場合</li>
        <li>その他、運営者が本サービスの利用を適当でないと判断した場合</li>
      </ol>
      <br>
      <p class="mb-4">運営者は，本条に基づき運営者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第7条（退会）</h2>
      <p class="mb-4">ユーザーは、運営者が定める手続に従って、本サービスから退会することができます。退会後は本サービスのすべての機能が利用できなくなることに同意するものとします(退会手続きについてはサービス開発中となります。ご了承ください)。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第8条（保証の否認および免責事項）</h2>
      <p class="mb-4">運営者は、本サービスに事実上または法律上の瑕疵（安全性、正確性、完全性など）がないことを保証しません。また、運営者は本サービスの利用によって生じた損害について、一切の責任を負いません。ただし、消費者契約法に基づく場合を除きます。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第9条（サービス内容の変更等）</h2>
      <p class="mb-4">運営者は、ユーザーへの事前通知をもって、本サービスの内容を変更、追加または廃止することができます。ユーザーは、この変更に異議なく同意するものとします。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第10条（利用規約の変更）</h2>
      <p class="mb-4">運営者は、次の場合、ユーザーの個別の同意を要せず、本規約を変更することができます。</p>
      <ol class="list-decimal pl-6 space-y-2">
        <li>本規約の変更がユーザーの一般の利益に適合するとき</li>
        <li>本規約の変更が本サービスの利用目的に反せず、合理的なものであるとき</li>
      </ol>
      <br>
      <p class="mb-4">運営者は、規約の変更について、事前にユーザーに通知します。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第11条（個人情報の取扱い）</h2>
      <p class="mb-4">運営者は、本サービスの利用によって取得するユーザーの個人情報について、別途定める<%= link_to "プライバシーポリシー", privacy_policy_path, class: "link" %>に従い適切に取り扱います。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第12条（通知または連絡）</h2>
      <p class="mb-4">ユーザーと運営者との間の通知や連絡は、運営者が定めた方法によって行います。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第13条（権利義務の譲渡の禁止）</h2>
      <p class="mb-4">ユーザーは、運営者の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利義務を第三者に譲渡し、または担保に供することはできません。</p>
    </div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold mb-4">第14条（準拠法・裁判管轄）</h2>
      <p>本規約の解釈にあたっては、日本法を準拠法とします。<br>本サービスに関して紛争が生じた場合には、運営者の本店所在地を管轄する裁判所を専属的合意管轄とします。</p>
    </div>
    <p>2024年9月11日 制定</p>
  </div>
</div>

app/views/static_pages/top.html.erb
<% content_for(:tab_title, "Stay Friends") %>

<!-- コメント削除すると本番環境にてデザインが崩れるため一旦残しておく
<div class="min-h-screen bg-cover flex flex-col md:flex-row">
  <div id="left-side" class="md:w-1/2 flex items-center flex-col mt-32 md:mt-40">
    <div id="left-text" class="text-white text-center">
      <h1 class="text-4xl md:text-4xl lg:text-5xl xl:text-6xl text-shadow-gray-md mb-3 md:mb-10">また、つながろう。</h1>
      <h1 class="text-4xl md:text-4xl lg:text-5xl xl:text-6xl text-shadow-gray-md mb-6 md:mb-12">私の大切なともだちと</h1>
    </div>
    <div class="bg-white bg-opacity-20 w-fit p-2 rounded-xl text-center">
      <p class="text-base md:text-lg lg:text-2xl font-medium text-black md:text-shadow-white mb-2">昔のともだちに、連絡を取ってみませんか？</p>
      <p class="text-base md:text-lg lg:text-2xl font-medium text-black md:text-shadow-white mb-2 md:mb-0">３つの質問に答えるだけで、</p>
      <p class="text-base md:text-lg lg:text-2xl font-medium text-black md:text-shadow-white">最適なメッセージを提案します</p>
    </div>
    <div id="left-button" class="flex justify-center mt-6">
      <%= link_to introduction_path(1) do %>
        <button class="btn bg-golden text-black border-none hover:bg-yellow-500 shadow-2xl">メッセージを作成する</button>
      <% end %>
    </div>
  </div>
  <div id="right-side" class="md:w-1/2 flex flex-col items-center justify-end mb-32 mt-20 md:mt-20">
    <div id="right-text" class="text-white text-center">
      <h1 class="text-4xl md:text-4xl lg:text-5xl xl:text-6xl text-shadow-gray-lg mb-3 md:mb-10">つながりつづけよう。</h1>
      <h1 class="text-4xl md:text-4xl lg:text-5xl xl:text-6xl text-shadow-gray-lg mb-6 md:mb-12">これからも、ずっと</h1>
    </div>
    <div class="bg-white bg-opacity-20 w-fit p-2 rounded-xl text-center">
      <p class="text-base md:text-lg lg:text-2xl font-medium text-black md:text-shadow-white mb-2">ともだちの大切な日が近づくと</p>
      <p class="text-base md:text-lg lg:text-2xl font-medium text-black md:text-shadow-white">LINE通知を受け取れます</p>
    </div>
    <div id="right-button" class="flex justify-center mt-6">
      <%= link_to profiles_path do %>
        <button class="btn bg-peach-red text-black border-none hover:bg-red-500 shadow-2xl">ともだち帳をひらく</button>
      <% end %>
    </div>
    </div>
  </div>
</div>
-->

<div class="grid grid-cols-1 md:grid-cols-2 h-full items-center" style="background-color: #FFFFF0;">
  <div class="flex flex-col justify-center">
    <%= image_tag("ogp.png") %>
    <div class="flex flex-col items-center">
      <div id="buttons" class="flex justify-center space-x-2 md:space-x-14 mt-4 sm:mt-0">
        <div id="button-1" class="space-y-2">
          <div class="flex justify-center">
            <%= link_to introduction_path(1) do %>
              <button class="btn bg-golden text-black border-none hover:bg-yellow-500 shadow-2xl">メッセージを作成する</button>
            <% end %>
          </div>
          <div class="w-fit sm:p-2 rounded-xl text-center">
            <p class="text-xs md:text-base text-black md:text-shadow-white">３つの質問に答えるだけで、</p>
            <p class="text-xs md:text-base text-black md:text-shadow-white">友だちに送る<br class="sm:hidden">最適なメッセージを提案します。</p>
          </div>
        </div>
        <div id="button-2" class="space-y-2">
          <div id="right-button" class="flex justify-center">
            <%= link_to profiles_path do %>
              <button class="btn bg-peach-red text-black border-none hover:bg-red-500 shadow-2xl">連絡帳をひらく</button>
            <% end %>
          </div>
          <div class="w-fit sm:p-2 rounded-xl text-center">
            <p class="text-xs md:text-base text-black md:text-shadow-white">友だちの大切な日を登録すると</p>
            <p class="text-xs md:text-base text-black md:text-shadow-white">LINEでリマインド通知を<br class="sm:hidden">受け取れます。</p>
          </div>
        </div>
      </div>
      <div class="mt-10">
        <%= link_to how_to_use_path do %>
          使い方
          <i class="fa-regular fa-circle-question"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="flex justify-center mt-5 md:mt-0">
    <%= image_tag "kids.jpg", class: "shadow-2xl hidden md:block" %>
  </div>
</div>

<!-- コメント削除すると本番環境にてデザインが崩れるため一旦残しておく
<div class="bg-ivory h-full bg-cover flex flex-col items-center md:flex-row">
  <div id="left-side" class="lg:w-1/2 flex items-center flex-col lg:mt-12 lg:ml-8">
    <div class="max-w-full">
      <%= image_tag("ogp.png", style: "width: 90%;") %>
    </div>
    <div id="buttons" class="flex space-x-2 sm:space-x-10 mt-4 sm:mt-0">
      <div id="button-1" class="space-y-2">
        <div class="flex justify-center">
          <%= link_to introduction_path(1) do %>
            <button class="btn bg-golden text-black border-none hover:bg-yellow-500 shadow-2xl text-xs">メッセージを作成する</button>
          <% end %>
        </div>
        <div class="w-fit sm:p-2 rounded-xl text-center">
          <p class="text-xs sm:text-sm md:text-sm lg:text-sm text-black md:text-shadow-white">３つの質問に答えるだけで、</p>
          <p class="text-xs sm:text-sm md:text-sm lg:text-sm text-black md:text-shadow-white">友だちに送る<br class="sm:hidden">最適なメッセージを提案します。</p>
        </div>
      </div>
      <div id="button-2" class="space-y-2">
        <div id="right-button" class="flex justify-center">
          <%= link_to profiles_path do %>
            <button class="btn bg-peach-red text-black border-none hover:bg-red-500 shadow-2xl">連絡帳をひらく</button>
          <% end %>
        </div>
        <div class="w-fit sm:p-2 rounded-xl text-center">
          <p class="text-xs sm:text-sm md:text-sm lg:text-sm text-black md:text-shadow-white">友だちの大切な日を登録すると</p>
          <p class="text-xs sm:text-sm md:text-sm lg:text-sm text-black md:text-shadow-white">LINEでリマインド通知を<br class="sm:hidden">受け取れます。</p>
        </div>
      </div>
    </div>
    <div id="how_to_use_1" class="mt-20 hidden lg:block">
      <%= link_to how_to_use_path do %>
        使い方
        <i class="fa-regular fa-circle-question"></i>
      <% end %>
    </div>
  </div>
  <div id="right-side" class="lg:w-1/2 flex flex-col items-center mt-10 sm:mt-4 md:mt-4 lg:mt-48">
    <%= image_tag("kids.jpg", class: "shadow-2xl", style: "width: 80%;") %>
    <div id="how_to_use_2" class="md:mt-4 hidden md:block lg:hidden">
      <%= link_to how_to_use_path do %>
        使い方
        <i class="fa-regular fa-circle-question"></i>
      <% end %>
    </div>
  </div>
</div>
-->