config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'static_pages#top'
  resources :introductions, only: [:show]
  resources :questions, only: [:show]
  resources :answers, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :profiles do
    resources :events do
      collection do
        patch :update_all
      end
    end
    resources :albums
  end
  resources :calendars, only: [:index]
  resources :groups, only: [:create, :index, :edit, :update, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ai_message', to: 'openai_api#show'

  get 'line_qr_code', to: 'static_pages#line_qr_code'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'
  get 'how_to_use', to: 'static_pages#how_to_use'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :images, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  has_many :profiles, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :events, through: :profiles

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :notification_enabled, presence: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  enum notification_enabled: { off: false, on: true }

  def self.only_ready_to_notify
    where.not(line_user_id: nil).where(notification_enabled: :on)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[show edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(user_params[:email], user_params[:password])
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to root_path
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to user_path(@user)
    else
      flash[:danger] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :notification_enabled)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/edit.html.erb
<% content_for(:tab_title, "マイページ") %>
<div class="flex flex-col items-center">
  <div id="card" class="md:border md:rounded-3xl md:border-slate-100 md:p-10 md:mt-10 md:bg-opacity-10 md:shadow-2xl h-full overflow-auto">
    <div class="flex flex-col items-center">
      <h1 class="text-3xl font-bold pt-10 md:pt-0 pb-10">マイページ</h1>
      <%= form_with model: @user, data: { turbo: false } do |f| %>
        <div class="mb-4">
          <%= f.label :name, "名前", class: "block font-medium mb-1 text-black" %>
          <%= f.text_field :name, class: "w-full rounded p-2 bg-white border border-black" %>
        </div>

        <div class="mb-4">
          <%= f.label :notification_enabled, "LINE通知", class: "block font-medium mb-1 text-black" %>
          <div class="col-span-1 flex items-center">
            <%= f.select :notification_enabled, [["ON", "on"], ["OFF", "off"]] %>
          </div>
        </div>

        <div class="flex justify-center">
          <%= f.submit "更新", class: "btn bg-golden text-black border-none hover:bg-yellow-500" %>
        </div>
      <% end %>

      <div class="mt-6">
        <% unless @user.authentications.exists? %>
          <%= link_to new_password_reset_path do %>
            パスワードの変更は<span class="underline underline-offset-1">こちら</span>から
          <% end %>
        <% end %>
      </div>
      <div id="notice" class="flex flex-col items-center mt-6 text-center">
        <div>
          <p>※通知機能は、</p>
          <%= link_to line_qr_code_path, class:"underline underline-offset-1"	do %>
            LINE友達登録
          <% end %>
          が必要です。
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:tab_title, "新規登録") %>

<div class="flex flex-col items-center">
  <h1 class="text-3xl font-bold pt-20 pb-10">ユーザー登録</h1>
  <%= form_with model: @user do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="mb-4">
      <%= f.label :name, "名前", class: "block font-medium mb-1 text-black" %>
      <%= f.text_field :name, class: "w-full rounded p-2 bg-white border border-black" %>
    </div>
    <div class="mb-4">
      <%= f.label :email, "メールアドレス", class: "block font-medium mb-1 text-black" %>
      <%= f.email_field :email, class: "w-full rounded p-2 bg-white border border-black" %>
    </div>
    <div class="mb-4">
      <%= f.label :password, "パスワード", class: "block font-medium mb-1 text-black" %>
      <%= f.password_field :password, class: "w-full rounded p-2 bg-white border border-black" %>
    </div>
    <div class="mb-4">
      <%= f.label :password_confirmation, "パスワード再入力", class: "block font-medium mb-1 text-black" %>
      <%= f.password_field :password_confirmation, class: "w-full rounded p-2 bg-white border border-black" %>
    </div>
    <div class="flex justify-center">
      <%= f.submit "登録", class: "btn bg-golden text-black border-none hover:bg-yellow-500" %>
    </div>
  <% end %>

  <%= link_to auth_at_provider_path(provider: :line) do %>
    <%= image_tag "btn_login_base.png", class:"w-32 h-auto mt-6"%>
  <% end %>

  <div class='mt-6'>
    <%= link_to login_path do %>
    <span class="underline underline-offset-1">ログインページへ</span>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:tab_title, "マイページ") %>

<div class="flex flex-col items-center">
  <div id="card" class="md:border md:rounded-3xl md:border-slate-100 md:px-28 py-20 md:mt-10 md:bg-opacity-10 md:shadow-2xl h-full overflow-auto">
    <h1 class="text-3xl font-bold pt-10 md:pt-0 pb-10">マイページ</h1>
    <div>
      <div class="mb-4">
        <p class="block font-medium mb-1 text-black">ユーザー名</p>
        <%= @user.name %>
      </div>

      <div class="mb-4">
        <p class="block font-medium mb-1 text-black">LINE通知設定</p>
        <%= @user.notification_enabled == "on" ? "ON" : "OFF" %>
      </div>

    </div>
    <div class="mt-6 flex justify-center">
      <%= link_to "編集", edit_user_path(@user), class: "btn bg-golden text-black border-none hover:bg-yellow-500" %>
    </div>
  </div>
</div>