config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'static_pages#top'
  resources :introductions, only: [:show]
  resources :questions, only: [:show]
  resources :answers, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :profiles do
    resources :events do
      collection do
        patch :update_all
      end
    end
    resources :albums
  end
  resources :calendars, only: [:index]
  resources :groups, only: [:create, :index, :edit, :update, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ai_message', to: 'openai_api#show'

  get 'line_qr_code', to: 'static_pages#line_qr_code'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'
  get 'how_to_use', to: 'static_pages#how_to_use'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :images, only: [:destroy]
end

app/views/shared/_before_login_footer.html.erb
<!---スマホ画面用のフッター--->
<footer id="mobile-footer" class="fixed bottom-0 flex items-center justify-center h-12 bg-zinc-600 w-full md:hidden">
  <div class="flex justify-around text-white text-xs w-full">
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to introduction_path(1) do %>
          <i class="fa-regular fa-message fa-lg"></i>
          <p>AIメッセージ</p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to profiles_path do %>
          <i class="fa-regular fa-address-book fa-lg"></i>
          <p>連絡帳</p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col justify-center text-center">
      <%= link_to how_to_use_path do %>
        <i class="fa-regular fa-circle-question fa-lg"></i>
        <p>使い方</p>
      <% end %>
    </div>
    <div class="flex flex-col justify-center text-center">
      <%= link_to login_path do %>
        <i class="fa-solid fa-arrow-right-to-bracket fa-lg"></i>
        <p>ログイン</p>
      <% end %>
    </div>
    <div class="flex flex-col justify-center text-center">
      <%= link_to new_user_path do %>
        <i class="fa-solid fa-user-plus fa-lg"></i>
        <p>新規登録</p>
      <% end %>
    </div>
  </div>
</footer>


<!---PC画面用のフッター--->
<footer id="pc-footer" class="bottom-0 bg-cream-pink w-full left-0 hidden md:block min-h-10">
  <div class="flex justify-center items-center space-x-20 h-full">
    <%= link_to "利用規約", terms_path %>
    <%= link_to "プライバシーポリシー", privacy_policy_path %>
    <%= link_to "お問い合わせ", "https://forms.gle/jj8fcaibi2Tvb9Yt7" %>
  </div>
</footer>

app/views/shared/_before_login_header.html.erb
<header class="top-0 left-0 w-full h-14 md:block flex justify-center bg-peach-light">
  <nav class="flex justify-between items-center h-14 w-full">
    <div class="flex items-center md:ml-8">
      <%= image_tag "logo.png", class:"w-10 h-auto mr-2 mb-2"%>
      <%= link_to root_path do %>
        <span class="text-lg md:text-4xl">Stay Friends</span><span class="text-xs md:text-xl"> ～友だちと再びつながるアプリ～</span>
      <% end %>
    </div>
    <div id="pc-nav" class="font-bold space-x-5 mr-5 hidden lg:block md:text-sm lg:text-md xl:text-base">
      <%= link_to "AIメッセージ作成", introduction_path(1) %>
      <%= link_to "連絡帳", profiles_path %>
      <%= link_to how_to_use_path do %>
        使い方
        <i class="fa-regular fa-circle-question"></i>
      <% end %>
      <%= link_to "ログイン", login_path %>
      <%= link_to new_user_path do %>
        <button class="btn bg-ivory-white text-black border-none hover:bg-peach-red <%= "hover:bg-slate-300" if current_page?(root_path) %>">新規登録</button>
      <% end %>
    </div>
    <div id="mobile-nav" class="navbar-end drawer-end w-fit lg:hidden">
      <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <!-- Page content here -->
        <label id="open-drawer" for="my-drawer-4" class="drawer-button btn btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 12.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 18.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5Z" /></svg>  
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <div class="p-4 pt-10 w-fit min-h-full bg-ivory-white text-black text-sm">
          <!-- Sidebar content here -->
          <div><%= link_to "AIメッセージ作成", introduction_path(1) %></div>
          <div><%= link_to "連絡帳", profiles_path %></div>
          <div class="divider divider-neutral"></div>
          <div>
            <%= link_to how_to_use_path do %>
              使い方
              <i class="fa-regular fa-circle-question"></i>
            <% end %>
          </div>
          <div><%= link_to "ログイン", login_path %></div>
          <div>
            <%= link_to "新規登録", new_user_path %>
          </div>
          <div class="divider divider-neutral"></div>
          <div><%= link_to "利用規約", terms_path %></div>
          <div><%= link_to "プライバシーポリシー", privacy_policy_path %></div>
          <div><%= link_to "お問い合わせ", "https://forms.gle/jj8fcaibi2Tvb9Yt7" %></div>

          <div class="divider divider-neutral"></div>
          <div><p>©️ 2024 - Stay Friends</p></div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<div class="text-red-500" id="error_message">
  <% if model.errors.any? %>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_flash_message.html.erb
<div class="flex justify-center" id="flash_message" >
  <% flash.each do |message_type, message| %>
    <div role= alert class="alert bg-ivory-white border border-4
      <%= case message_type
          when "success" then "alert-success border-green-600"
          when "warning" then "alert-warning border-orange-600"
          when "danger" then "alert-danger border-red-600"
          end %>
      <%= "absolute top-14" if current_page?(root_path) %>">
      <div class="text-black font-bold"><%= message %></div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<!---スマホ画面用のフッター--->
<footer id="mobile-footer" class="fixed bottom-0 flex items-center justify-center h-12 bg-zinc-600 w-full md:hidden">
  <div class="flex justify-around text-white text-xs w-full">
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to introduction_path(1) do %>
          <i class="fa-regular fa-message fa-lg"></i>
          <p>AIメッセージ</p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to profiles_path do %>
          <i class="fa-regular fa-address-book fa-lg"></i>
          <p>連絡帳</p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to user_path(current_user) do %>
          <i class="fa-regular fa-user fa-lg"></i>
          <p>マイページ</p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col justify-center text-center">
      <%= link_to how_to_use_path do %>
        <i class="fa-regular fa-circle-question fa-lg"></i>
        <p>使い方</p>
      <% end %>
    </div>
    <div class="flex flex-col justify-center text-center">
      <div>
        <%= link_to logout_path, data: { turbo_method: :delete } do %>
          <i class="fa-solid fa-arrow-right-from-bracket fa-lg"></i>
          <p>ログアウト</p>
        <% end %>
      </div>
    </div>
  </div>
</footer>


<!---PC画面用のフッター--->
<footer id="pc-footer" class="bottom-0 bg-cream-pink w-full left-0 hidden md:block min-h-10">
  <div class="flex justify-center items-center space-x-20 h-full">
    <%= link_to "利用規約", terms_path %>
    <%= link_to "プライバシーポリシー", privacy_policy_path %>
    <%= link_to "お問い合わせ", "https://forms.gle/jj8fcaibi2Tvb9Yt7" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="top-0 left-0 w-full h-14 md:block flex justify-center bg-peach-light">
  <nav class="flex justify-between items-center h-14 w-full">
    <div class="flex items-center ml-2 md:ml-8">
      <%= image_tag "logo.png", class:"w-10 h-auto mr-2 mb-2"%>
      <%= link_to root_path do %>
        <span class="text-lg md:text-4xl">Stay Friends</span><span class="text-xs md:text-xl"> ～友だちと再びつながるアプリ～</span>
      <% end %>
    </div>
    <div id="pc-nav" class="font-bold space-x-5 mr-5 hidden lg:block md:text-sm lg:text-md xl:text-base">
      <%= link_to "AIメッセージ作成", introduction_path(1) %>
      <%= link_to "連絡帳", profiles_path %>
      <%= link_to "カレンダー", calendars_path %>
      <%= link_to how_to_use_path do %>
        使い方
        <i class="fa-regular fa-circle-question"></i>
      <% end %>
      <%= link_to "マイページ", user_path(current_user)  %>
      <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %>
    </div>

    <div id="mobile-nav" class="navbar-end drawer-end w-fit lg:hidden">
      <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <!-- Page content here -->
        <label id="open-drawer" for="my-drawer-4" class="drawer-button btn btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 12.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 18.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5Z" /></svg>  
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <div class="p-4 pt-10 w-fit min-h-full bg-ivory-white text-black text-sm">
          <!-- Sidebar content here -->
          <div><%= link_to "AIメッセージ作成", introduction_path(1) %></div>
          <div><%= link_to "連絡帳", profiles_path %></div>
          <div><%= link_to "カレンダー", calendars_path %></div>
          <div class="divider divider-neutral"></div>
          <div>
            <%= link_to how_to_use_path do %>
              使い方
              <i class="fa-regular fa-circle-question"></i>
            <% end %>
          </div>
          <div><%= link_to "マイページ", user_path(current_user)  %></div>
          <div><%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %></div>

          <div class="divider divider-neutral"></div>
          <div><%= link_to "利用規約", terms_path %></div>
          <div><%= link_to "プライバシーポリシー", privacy_policy_path %></div>
          <div><%= link_to "お問い合わせ", "https://forms.gle/jj8fcaibi2Tvb9Yt7" %></div>

          <div class="divider divider-neutral"></div>
          <div><p>©️ 2024 - Stay Friends</p></div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<aside id="default-sidebar" class="w-64 h-full transition-transform -translate-x-full sm:translate-x-0 hidden md:block" aria-label="Sidebar">
  <div class="h-full px-4  overflow-y-auto bg-stone-200 text-gray-900">
      <div class="flex items-center justify-center mt-4 mb-20">
        <% if profile.avatar.persisted? && profile.avatar.attached? && profile.avatar.content_type.in?(%w[image/jpeg image/png]) %>
          <%= image_tag profile.avatar.variant(resize_to_limit: [50, 50]) %>
        <% else %>
          <%= image_tag "default_avatar.png", style: "width: 50px; height: 50px;" %>
        <% end %>
        <p class="text-lg font-bold"><%= @profile.name%></p>
      </div>
      <ul class="space-y-10 font-medium text-lg">
        <li class=
            "px-4 py-2 rounded-lg hover:bg-gray-100
            <%= sidebar_active_class(profile_path(profile))%>
            <%= sidebar_active_class(new_profile_path(profile))%>
            <%= sidebar_active_class(edit_profile_path(profile))%>
          ">
          <%= link_to "基本情報", profile_path(profile), class: "block w-full h-full" %>
        </li>
        <li class=
            "px-4 py-2 rounded-lg hover:bg-gray-100
            <%= sidebar_active_class(profile_albums_path(profile)) %>
            <%= sidebar_active_class(profile_album_path(profile, album)) if defined?(album) && album.persisted? %>
            <%= sidebar_active_class(edit_profile_album_path(profile, album)) if defined?(album) && album.persisted? %>
            <%= sidebar_active_class(new_profile_album_path(profile, album)) if defined?(album) %>
          ">
          <%= link_to "アルバム", profile_albums_path(profile), class: "block w-full h-full" %>
        </li>
        <li class=
            "px-4 py-2 rounded-lg hover:bg-gray-100
            <%= sidebar_active_class(profile_events_path(profile)) %>
          ">
          <%= link_to "通知設定", profile_events_path(profile), class: "block w-full h-full" %>
        </li>
        <li class="px-4 py-2 rounded-lg hover:bg-gray-100">
          <%= link_to profiles_path, class: "block w-full h-full" do %>
            連絡先一覧
          <% end %>
        </li>
      </ul>
  </div>
</aside>

app/views/shared/_top_tab.html.erb
<div id="top-tab" role="tablist" class="tabs tabs-bordered mt-3 px-1 md:hidden">
  <%= link_to "基本情報",
              profile_path(profile),
              role: "tab",
              class:
                "tab text-black rounded
                #{top_tab_active_class(profile_path(profile))}
                #{top_tab_active_class(new_profile_path(profile))}
                #{top_tab_active_class(edit_profile_path(profile))}
              " %>
  <%= link_to "アルバム",
              profile_albums_path(profile),
              role: "tab",
              class:
                "tab text-black rounded
                #{ top_tab_active_class(profile_albums_path(profile)) }
                #{ top_tab_active_class(profile_album_path(profile, album)) if defined?(album) && album.persisted? }
                #{ top_tab_active_class(edit_profile_album_path(profile, album)) if defined?(album) && album.persisted? }
                #{ top_tab_active_class(new_profile_album_path(profile, album)) if defined?(album) }
              " %>
  <%= link_to "通知設定",
              profile_events_path(profile),
              role: "tab",
              class: "tab text-black rounded #{top_tab_active_class(profile_events_path(profile))}" %>
</div>