config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'static_pages#top'
  resources :introductions, only: [:show]
  resources :questions, only: [:show]
  resources :answers, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :profiles do
    resources :events do
      collection do
        patch :update_all
      end
    end
    resources :albums
  end
  resources :calendars, only: [:index]
  resources :groups, only: [:create, :index, :edit, :update, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ai_message', to: 'openai_api#show'

  get 'line_qr_code', to: 'static_pages#line_qr_code'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'
  get 'how_to_use', to: 'static_pages#how_to_use'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :images, only: [:destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :profile

  enum notification_enabled: { off: false, on: true }

  validate :check_number_of_events, on: :create

  def ready_to_notify?
    date.present? && notification_timing.present? && notification_enabled?
  end

  def scheduled_to_notify_today?
    event_date_this_year - utc_today_to_jst.to_date == notification_timing
  end

  def event_date_this_year
    Date.new(Date.today.year, date.mon, date.mday)
  end

  def utc_today_to_jst
    DateTime.now + 9.hours
  end

  def check_number_of_events
    errors.add(:events, "大切な日は１つまでしか登録できません") if profile&.events&.count == Settings.event_count.max_count
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @profile = current_user.profiles.find(params[:profile_id])
    @form = Form::EventCollection.new(events: @profile.events)
  end

  def update_all
    @form = Form::EventCollection.new(event_params)
    if @form.update
      flash[:success] = "保存しました"
      redirect_to profile_events_path(@form.profile_id)
    else
      flash.now[:success] = "保存できませんでした"
      render :index, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:form_event_collection).permit(
      events_attributes: %i[
        id name date notification_timing notification_enabled profile_id
      ]
    )
  end
end

app/views/events/_notification_off.html.erb
<div class="w-full text-black md:text-base lg:text-2xl">
  <%= form_with model: @form, url: update_all_profile_events_path, method: :patch, data: { turbo: false } do |f| %>
    <fieldset disabled="disabled">
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.fields_for :events do |i| %>
        <div class="grid grid-cols-2 lg:grid-cols-3 items-center gap-1 mb-4 text-center" data-index="<%= i.index %>">
          <div>
            <%= "#{i.object.name}の" %>
          </div>
          <div class="flex items-center space-x-1">
            <%= i.select :notification_timing, [0,1,3,7,14,30,60], selected: i.object.notification_timing, class: "text-black w-full" %>
            <p>日前に</p>
          </div>
          <div class="flex items-center space-x-1 col-span-2 col-start-2 lg:col-span-1">
            <p>通知</p>
            <%= i.select :notification_enabled, ["しない"], class: "p-0" %>
          </div>
          <div>
            <%= i.hidden_field :date, value: i.object.date %>
            <%= i.hidden_field :name, value: i.object.name %>
            <%= i.hidden_field :profile_id, value: i.object.profile_id %>
          </div>
        </div>
      <% end %>
      <div class="flex justify-center">
        <%= f.submit '登録する', class: "btn bg-slate-300 text-black border-none" %>
      </div>
    </fieldset>
  <% end %>
</div>
<div class="flex justify-center mt-10 text-sm lg:text-xl">
  <div class="text-center text-red-500">
    <p>※マイページの通知設定がOFFのため、<br class="md:hidden">変更できません</p>
    マイページは<%= link_to "こちら", edit_user_path(@profile.user), class: "underline underline-offset-1" %>
  </div>
</div>

app/views/events/_notification_on.html.erb
<div class="w-full text-black text-sm md:text-base lg:text-2xl">
  <%= form_with model: @form, url: update_all_profile_events_path, method: :patch, data: { turbo: false } do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%= f.fields_for :events do |i| %>
      <div class="grid grid-cols-2 lg:grid-cols-3 items-center gap-1 mb-4 text-center" data-index="<%= i.index %>">
        <div>
          <%= "#{i.object.name}の" %>
        </div>
        <div class="flex items-center space-x-1">
          <%= i.select :notification_timing, [0,1,3,7,14,30,60], selected: i.object.notification_timing, class: "text-black w-full" %>
          <p>日前に</p>
        </div>
        <div class="flex items-center space-x-1 col-span-2 col-start-2 lg:col-span-1">
          <p>通知</p>
        <%= i.select :notification_enabled, [["する", "on"], ["しない", "off"]] %>
        </div>
        <div>
          <%= i.hidden_field :date, value: i.object.date %>
          <%= i.hidden_field :name, value: i.object.name %>
          <%= i.hidden_field :profile_id, value: i.object.profile_id %>
        </div>
      </div>
    <% end %>
    <div class="flex justify-center">
      <%= f.submit '登録する', class: "btn bg-golden text-black border-none hover:bg-yellow-500" %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<% content_for(:tab_title, "通知設定") %>

<div id="outer-frame" class="flex h-full flex-col md:flex-row">
  <%= render "shared/sidebar", profile: @profile%>
  <%= render "shared/top_tab", profile: @profile%>

  <div id="right-section" class="h-full w-full flex justify-center">
    <div id="card" class="w-full h-fit mt-20 md:p-10 md:flex flex-col md:border md:rounded-3xl md:border-slate-100 md:bg-opacity-10 md:shadow-2xl md:w-2/3 mb-20 md:mb-0">
      <% if @profile.user.notification_enabled == "off" %>
        <%= render "notification_off" %>
      <% else %>
        <%= render "notification_on" %>
      <% end %>
      <div id="notice" class="flex flex-col items-center mt-10 lg:text-xl text-sm">
        <div>
          <p>※通知機能は、</p>
          <%= link_to line_qr_code_path, class:"underline underline-offset-1"	do %>
            LINE友達登録
          <% end %>
          が必要です。
        </div>
      </div>
    </div>
  </div>
</div>